package com.example.demojava11;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.MockedStatic;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.boot.SpringApplication;
import org.springframework.context.ConfigurableApplicationContext;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.mockStatic;
import static org.mockito.Mockito.times;

@ExtendWith(MockitoExtension.class)
class DemoJava11ApplicationTest {

    /**
     * Verifies that the main method can be invoked without throwing any exception,
     * by mocking the static SpringApplication.run call to avoid starting a real
     * application context during unit testing.
     */
    @Test
    void main_shouldRunWithoutThrowing() {
        try (MockedStatic<SpringApplication> mockedSpringApplication = mockStatic(SpringApplication.class)) {

            ConfigurableApplicationContext mockContext = mock(ConfigurableApplicationContext.class);

            mockedSpringApplication
                    .when(() -> SpringApplication.run(eq(DemoJava11Application.class), any(String[].class)))
                    .thenReturn(mockContext);

            assertDoesNotThrow(() -> DemoJava11Application.main(new String[]{}),
                    "main() should not throw any exception when SpringApplication.run is mocked");

            mockedSpringApplication.verify(
                    () -> SpringApplication.run(eq(DemoJava11Application.class), any(String[].class)),
                    times(1)
            );
        }
    }

    /**
     * Verifies that the main method forwards the provided arguments to SpringApplication.run.
     */
    @Test
    void main_shouldForwardArgsToSpringApplication() {
        var args = new String[]{"--server.port=8081", "--spring.profiles.active=test"};

        try (MockedStatic<SpringApplication> mockedSpringApplication = mockStatic(SpringApplication.class)) {

            ConfigurableApplicationContext mockContext = mock(ConfigurableApplicationContext.class);

            mockedSpringApplication
                    .when(() -> SpringApplication.run(eq(DemoJava11Application.class), eq(args)))
                    .thenReturn(mockContext);

            assertDoesNotThrow(() -> DemoJava11Application.main(args),
                    "main() should not throw any exception with custom args");

            mockedSpringApplication.verify(
                    () -> SpringApplication.run(eq(DemoJava11Application.class), eq(args)),
                    times(1)
            );
        }
    }

    /**
     * Verifies that the main method handles a null args array gracefully
     * when SpringApplication.run is mocked, relying on Spring Boot's own null-safety.
     */
    @Test
    void main_shouldHandleNullArgs() {
        try (MockedStatic<SpringApplication> mockedSpringApplication = mockStatic(SpringApplication.class)) {

            ConfigurableApplicationContext mockContext = mock(ConfigurableApplicationContext.class);

            mockedSpringApplication
                    .when(() -> SpringApplication.run(eq(DemoJava11Application.class), any()))
                    .thenReturn(mockContext);

            // Even with null, the delegation to Spring should occur without a NullPointerException
            // at the application level — Spring Boot handles null args internally.
            assertDoesNotThrow(() -> DemoJava11Application.main(null),
                    "main() should delegate null args to SpringApplication without throwing");
        }
    }

    /**
     * Verifies that a DemoJava11Application instance can be created (covers
     * the implicit no-arg constructor generated by the compiler).
     */
    @Test
    void constructor_shouldInstantiateSuccessfully() {
        var application = new DemoJava11Application();
        assertNotNull(application, "DemoJava11Application instance should not be null");
    }
}
