package com.example.demojava11;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.MockedStatic;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.boot.SpringApplication;
import org.springframework.context.ConfigurableApplicationContext;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.mockStatic;
import static org.mockito.Mockito.times;

@ExtendWith(MockitoExtension.class)
class DemoJava11ApplicationTest {

    /**
     * Verifies that the main method can be invoked without throwing any exception,
     * using a mocked SpringApplication.run to avoid starting a real application context.
     */
    @Test
    void main_shouldRunWithoutException() {
        try (MockedStatic<SpringApplication> mockedSpringApplication = mockStatic(SpringApplication.class)) {

            ConfigurableApplicationContext mockContext =
                    Mockito.mock(ConfigurableApplicationContext.class);

            mockedSpringApplication
                    .when(() -> SpringApplication.run(
                            eq(DemoJava11Application.class),
                            any(String[].class)))
                    .thenReturn(mockContext);

            String[] args = {};

            assertDoesNotThrow(() -> DemoJava11Application.main(args),
                    "main() must not throw any exception");

            mockedSpringApplication.verify(
                    () -> SpringApplication.run(
                            eq(DemoJava11Application.class),
                            any(String[].class)),
                    times(1));
        }
    }

    /**
     * Verifies that the main method forwards the provided arguments to SpringApplication.run.
     */
    @Test
    void main_shouldForwardArgumentsToSpringApplication() {
        try (MockedStatic<SpringApplication> mockedSpringApplication = mockStatic(SpringApplication.class)) {

            ConfigurableApplicationContext mockContext =
                    Mockito.mock(ConfigurableApplicationContext.class);

            var args = new String[]{"--server.port=9090", "--spring.profiles.active=test"};

            mockedSpringApplication
                    .when(() -> SpringApplication.run(
                            eq(DemoJava11Application.class),
                            eq(args)))
                    .thenReturn(mockContext);

            assertDoesNotThrow(() -> DemoJava11Application.main(args),
                    "main() must not throw even when arguments are provided");

            mockedSpringApplication.verify(
                    () -> SpringApplication.run(
                            eq(DemoJava11Application.class),
                            eq(args)),
                    times(1));
        }
    }

    /**
     * Verifies that the main method handles a null-equivalent empty args array gracefully.
     */
    @Test
    void main_shouldHandleEmptyArgsArray() {
        try (MockedStatic<SpringApplication> mockedSpringApplication = mockStatic(SpringApplication.class)) {

            ConfigurableApplicationContext mockContext =
                    Mockito.mock(ConfigurableApplicationContext.class);

            mockedSpringApplication
                    .when(() -> SpringApplication.run(
                            eq(DemoJava11Application.class),
                            any(String[].class)))
                    .thenReturn(mockContext);

            assertDoesNotThrow(() -> DemoJava11Application.main(new String[0]),
                    "main() must not throw when an empty args array is passed");
        }
    }

    /**
     * Verifies that the DemoJava11Application class can be instantiated (public no-arg constructor
     * generated by the compiler must be accessible).
     */
    @Test
    void applicationClass_shouldBeInstantiable() {
        assertDoesNotThrow(() -> {
            var instance = new DemoJava11Application();
            assertNotNull(instance, "Instance must not be null");
        }, "DemoJava11Application must have an accessible no-arg constructor");
    }

    /**
     * Verifies that SpringApplication.run returns the mocked context and that the interaction
     * count stays exactly 1 for a single main() invocation.
     */
    @Test
    void main_shouldInvokeSpringApplicationRunExactlyOnce() {
        try (MockedStatic<SpringApplication> mockedSpringApplication = mockStatic(SpringApplication.class)) {

            ConfigurableApplicationContext mockContext =
                    Mockito.mock(ConfigurableApplicationContext.class);

            mockedSpringApplication
                    .when(() -> SpringApplication.run(
                            eq(DemoJava11Application.class),
                            any(String[].class)))
                    .thenReturn(mockContext);

            DemoJava11Application.main(new String[]{});

            // Confirm exactly one interaction — no accidental double-start
            mockedSpringApplication.verify(
                    () -> SpringApplication.run(
                            eq(DemoJava11Application.class),
                            any(String[].class)),
                    times(1));

            mockedSpringApplication.verifyNoMoreInteractions();
        }
    }
}
